server:
  port: 8086


spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: postgres
    password: "Welcome@1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8086


jwt:
  keystore:
    location: classpath:jwt-keystore.jks
    password: changeit
  key:
    alias: jwt-key
    password: changeit
    id: caerus-key-1


application:
  security:
    jwt:
      expiration: 900000 #  15 min in ms
      refresh-token:
        expiration: 1296000000 # 15 days in ms


cors:
  allowed-origins: "*"

services:
  user-service:
    url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.caerus.identity.client: DEBUG


resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 2s
